const state={story:'',part:'',pain:'',safety:{}};
let recognition=null;let listening=false;let stopRequested=false;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
$$('[data-go]').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.go)));
$$('#mechanismChips button').forEach(btn=>btn.addEventListener('click',()=>{$$('#mechanismChips button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');if(btn.dataset.value!=='기타')$('#storyInput').value=btn.dataset.value}));
function startVoice(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){toast('이 브라우저에서는 음성 입력을 사용할 수 있어요. 직접 적어주세요.');return}if(!recognition){recognition=new Speech();recognition.lang='ko-KR';recognition.continuous=true;recognition.interimResults=true;recognition.onstart=()=>{listening=true;stopRequested=false;$('#voiceLabel').textContent='듣는 중…';$('#voiceStatus').textContent='잠깐 멈춰도 괜찮아요. 다 말했으면 아래 버튼을 눌러주세요.';$('#doneSpeaking').disabled=false};recognition.onresult=e=>{let finalText='';let interimText='';for(let i=0;i<e.results.length;i++){if(e.results[i].isFinal)finalText+=e.results[i][0].transcript;else interimText+=e.results[i][0].transcript}const previous=$('#storyInput').dataset.finalText||'';if(finalText)$('#storyInput').dataset.finalText=previous+finalText;$('#storyInput').value=($('#storyInput').dataset.finalText||'')+interimText};recognition.onend=()=>{if(listening&&!stopRequested){setTimeout(()=>{try{recognition.start()}catch(e){}},150)}else{$('#voiceLabel').textContent='눌러서 말하기';$('#voiceStatus').textContent='입력이 끝났어요.';$('#doneSpeaking').disabled=true}};recognition.onerror=e=>{if(e.error==='not-allowed'){listening=false;stopRequested=true;toast('마이크 권한을 허용해 주세요.')}else if(e.error!=='no-speech'){toast('음성 입력을 다시 시도해 주세요.')}}}try{recognition.start()}catch(e){}}
$('#voiceButton').addEventListener('click',()=>{if(listening)toast('계속 듣고 있어요. 다 말했으면 아래 버튼을 눌러주세요.');else startVoice()});
$('#doneSpeaking').addEventListener('click',()=>{stopRequested=true;listening=false;if(recognition)recognition.stop();$('#storyInput').dataset.finalText=$('#storyInput').value;$('#voiceLabel').textContent='눌러서 말하기';$('#voiceStatus').textContent='입력이 끝났어요.';$('#doneSpeaking').disabled=true});
$('#continueIntake').addEventListener('click',()=>{state.story=$('#storyInput').value.trim()||'운동 중 부상';$('#summaryCard').innerHTML='<span class="summary-pill">'+state.story+'</span>';go('details')});
$$('#bodyGrid button').forEach(btn=>btn.addEventListener('click',()=>{$$('#bodyGrid button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.part=btn.dataset.part}));
$('#continueDetails').addEventListener('click',()=>{if(!state.part){toast('아픈 부위를 하나 눌러주세요.');return}const part=state.part;$('#safetyContext').textContent=part+'에 생길 수 있는 위험 신호를 기준으로 꼭 필요한 것만 확인해요.';$('#movementHint').textContent=['발목','무릎'].includes(part)?'다친 다리에 체중을 실을 수 있는지 확인해요.':['손목','팔꿈치'].includes(part)?'다친 팔로 물건을 잡거나 팔을 굽힐 수 있는지 확인해요.':'다친 부위를 평소처럼 움직일 수 있는지 확인해요.';$('#sensationHint').textContent='다친 '+part+'와 그 주변이 저리거나 감각이 둔한지 확인해요.';go('safety')});
$$('.segmented').forEach(group=>group.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;group.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');state.safety[group.dataset.key]=e.target.textContent}));
$('#continueSafety').addEventListener('click',()=>{if(state.safety.deform==='네'||state.safety.movement==='못 해요'||state.safety.sensation==='네'){state.pain=state.pain||'10';renderClinicalDecision()}else go('pain')});
$$('#painScale button').forEach(btn=>btn.addEventListener('click',()=>{$$('#painScale button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.pain=btn.dataset.pain}));
function renderClinicalDecision(){const story=state.story||'';const part=state.part||'다친 부위';const high=state.safety.deform==='네'||state.safety.movement==='못 해요'||state.safety.sensation==='네'||/뼈가 보|피가 많이|모양이 이상|의식|호흡|파란|회색|차가워|전혀 못/.test(story);const urgent=high||state.pain==='10';const sameDay=!urgent&&(state.safety.movement==='어려워요'||state.pain==='7'||/빠르게 붓|계속 붓|심하게 아|뚝|딱|갈리|잠기|꺾여/.test(story));let title=urgent?'지금은 앱보다 응급 도움을 먼저 받아요.':sameDay?'오늘 안에 의료기관에서 확인해요.':'현재는 초기 관리와 변화 관찰이 필요해요.';$('#resultTitle').innerHTML=title.replace(' ','<br/>');$('#resultTitle').classList.toggle('urgent-title',urgent);$('#resultTitle').classList.toggle('same-day-title',sameDay);$('#resultTitle').classList.toggle('watch-title',!urgent&&!sameDay);$('#candidateTitle').textContent=urgent?'골절·탈구·신경/혈액순환 문제를 먼저 확인해야 해요':sameDay?part+' 염좌·인대 손상 또는 뼈 손상 가능성':part+'의 가벼운 타박·염좌 가능성';$('#candidateDesc').textContent=urgent?'사진만으로 구분할 수 없습니다. 부위를 펴거나 맞추지 말고 즉시 의료진의 평가를 받으세요.':sameDay?'입력한 상황과 기능 제한은 더 확인이 필요한 상태와 비슷합니다. X-ray 등 검사가 필요할 수 있어요.':'위험 신호가 없고 기능이 유지되는 경우와 비슷합니다. 24~48시간 동안 통증·부종·기능 변화를 기록하세요.';$('#visitLevel').textContent=urgent?'즉시 119 또는 가까운 응급실':sameDay?'오늘 안에 정형외과 또는 응급의료기관':'24~48시간 관찰하되 악화되면 당일 진료';const action=$('.action-card');action.innerHTML='<h3>'+(urgent?'지금 바로 할 일':'지금 구체적으로 해볼 일')+'</h3>'+(urgent?'<div class="todo"><span>1</span><b>운동과 움직임을 멈추고 다친 부위를 펴거나 맞추지 마세요.</b></div><div class="todo"><span>2</span><b>출혈이 있으면 깨끗한 거즈로 직접 압박하세요. 뼈가 보이면 밀어 넣지 마세요.</b></div><div class="todo"><span>3</span><b>보호자·코치에게 즉시 알리고 119 또는 응급실로 이동하세요.</b></div>':'<div class="todo"><span>1</span><b>운동·달리기·점프를 멈추고 통증을 유발하는 동작을 반복하지 마세요.</b></div><div class="todo"><span>2</span><b>천으로 감싼 냉팩을 15~20분 대고 피부에 얼음을 직접 대지 마세요.</b></div><div class="todo"><span>3</span><b>다친 부위를 편하게 받치고 가능하면 심장보다 높게 올리세요.</b></div><div class="todo"><span>4</span><b>열찜질·음주·강한 마사지·통증을 유발하는 스트레칭은 초기 48~72시간 피하세요.</b></div><div class="todo"><span>5</span><b>저림·색 변화·통증 증가·사용 불가가 생기면 즉시 진료 경로로 바꾸세요.</b></div>');let recovery=document.querySelector('.return-card');if(!recovery){recovery=document.createElement('div');recovery.className='return-card';$('.visit-card').after(recovery)}recovery.innerHTML='<strong>운동 복귀 준비</strong><b>의료진 확인 후 5단계로 진행</b><div class="return-steps"><span>1 일상 걷기</span><span>2 움직임</span><span>3 기본 근력</span><span>4 종목 동작</span><span>5 다음날 확인</span></div><small>통증·절뚝거림·부종이 다시 늘면 복귀를 멈추고 이전 단계로 돌아가세요.</small>';if(urgent)go('result')}
$('#showResult').addEventListener('click',()=>{if(!state.pain){toast('통증에 가까운 얼굴을 눌러주세요.');return}renderClinicalDecision();go('result')});
$('#hospitalButton').addEventListener('click',()=>go('hospital'));$('#reportButton').addEventListener('click',()=>go('report'));$('#helpButton').addEventListener('click',()=>alert('나만의 A.T는 참고용 기록·대처 안내 서비스입니다. 위급하면 앱보다 119와 의료기관을 먼저 이용하세요.'));
document.querySelector('.report-title b').textContent='나만의 A.T 부상 기록';const teamPhoto=document.querySelector('.team-photo');if(teamPhoto){teamPhoto.src='assets/athlete-team-characters.png';teamPhoto.alt='함께 걷고 있는 두 명의 유소년 축구 선수 캐릭터'}document.querySelectorAll('.hospital-list article').forEach((card,i)=>{const row=document.createElement('div');row.className='price-row';row.innerHTML=i===0?'<span>초진 예상 본인부담</span><strong>약 10,000–30,000원</strong>':'<span>응급실 예상 본인부담</span><strong>약 30,000원 이상</strong>';card.querySelector('div:nth-child(2)').insertBefore(row,card.querySelector('.call-link'))});const clinicalCss=document.createElement('link');clinicalCss.rel='stylesheet';clinicalCss.href='clinical.css';document.head.appendChild(clinicalCss);
